Update `alt_memery` to a fixed version
```
~/Projects/ruby/flame
> toys g release 5.0.0.rc6
NoMethodError: undefined method `[]' for nil:NilClass
     37: /home/alex/.rbenv/versions/3.0.0/bin/toys:23:in `<main>'
     36: /home/alex/.rbenv/versions/3.0.0/bin/toys:23:in `load'
     35: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-0.11.4/bin/toys:11:in `<top (required)>'
     34: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:426:in `run'
     33: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/errors.rb:70:in `capture_path'
     32: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:434:in `block in run'
     31: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:466:in `run_tool'
     30: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:490:in `execute_tool_in_context'
     29: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:490:in `catch'
     28: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:491:in `block in execute_tool_in_context'
     27: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:522:in `block in make_executor'
     26: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/standard_middleware/show_help.rb:234:in `run'
     25: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:522:in `block in make_executor'
     24: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/standard_middleware/show_root_version.rb:67:in `run'
     23: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:522:in `block in make_executor'
     22: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/standard_middleware/handle_usage_errors.rb:39:in `run'
     21: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:480:in `block in execute_tool_in_context'
     20: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/tool.rb:1317:in `block in make_delegation_run_handler'
     19: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:426:in `run'
     18: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/errors.rb:70:in `capture_path'
     17: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:434:in `block in run'
     16: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:466:in `run_tool'
     15: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:490:in `execute_tool_in_context'
     14: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:490:in `catch'
     13: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:491:in `block in execute_tool_in_context'
     12: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:522:in `block in make_executor'
     11: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/standard_middleware/show_help.rb:234:in `run'
     10: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:522:in `block in make_executor'
      9: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/standard_middleware/show_root_version.rb:67:in `run'
      8: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:522:in `block in make_executor'
      7: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/standard_middleware/handle_usage_errors.rb:39:in `run'
      6: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/toys-core-0.11.4/lib/toys/cli.rb:480:in `block in execute_tool_in_context'
      5: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gem_toys-0.5.0/lib/gem_toys/template/release.rb:27:in `block (3 levels) in <class:Release>'
      4: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gem_toys-0.5.0/lib/gem_toys/template/release.rb:79:in `handle_new_version'
      3: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/alt_memery-2.0.0/lib/memery.rb:84:in `clear_memery_cache!'
      2: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/alt_memery-2.0.0/lib/memery.rb:84:in `each'
      1: /home/alex/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/alt_memery-2.0.0/lib/memery.rb:84:in `block in clear_memery_cache!'
Error during tool execution!
    NoMethodError: undefined method `[]' for nil:NilClass
    while executing tool: "gem release"
    with arguments: ["5.0.0.rc6"]
```